version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.1.1
  browser-tools: circleci/browser-tools@1.4.0

executors:
  node:
    docker:
      - image: cimg/node:14.20.1
  node-browsers:
    docker:
      - image: cimg/node:14.20.1-browsers

#############################################################
# Define workflows
#############################################################
workflows:
  version: 2
  pipeline:
    jobs:
      - install_dependencies      
      - build:
          requires:
            - install_dependencies
      - lint:
          requires:
            - install_dependencies
      - unit_tests:
          requires:
            - install_dependencies
      - deploy:
          context: AWS
          requires:
            - build
            - lint
            - unit_tests
          #filters:
          #  branches:
          #    only:
          #      - main

#############################################################
# Define jobs
#############################################################
jobs:
  install_dependencies:
    working_directory: ~/app
    executor: node
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: v1-{{ checksum "package.json" }}
          paths:
            - node_modules

  build:
    working_directory: ~/app
    executor: node
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ checksum "package.json" }}
      - run: npm install
      - run: npm run build -- --configuration=production
      - run: zip -r ./dist/paterson-web.zip ./dist/paterson-web
      - persist_to_workspace:
          root: .
          paths:
            - dist

  lint:
    working_directory: ~/app
    executor: node
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ checksum "package.json" }}
      - run: npm install
      - run: npm run lint

  unit_tests:
    working_directory: ~/app
    executor: node-browsers
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - restore_cache:
          key: v1-{{ checksum "package.json" }}
      - run: npm install
      - run: npm run test -- --watch=false --code-coverage
      - run: cat ./coverage/paterson-web/lcov.info  | ./node_modules/coveralls/bin/coveralls.js

  deploy:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - attach_workspace:
          at: .
      - aws-s3/sync:
          from: ./dist/paterson-web.zip
          to: 's3://jjpaters-deployer/paterson-web'
